<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit9bfb4efef2e4a56c70b688b9ced90ffd
{
    public static $prefixLengthsPsr4 = array (
        'P' => 
        array (
            'Psr\\Log\\' => 8,
        ),
        'M' => 
        array (
            'Mautic\\' => 7,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'Psr\\Log\\' => 
        array (
            0 => __DIR__ . '/..' . '/psr/log/Psr/Log',
        ),
        'Mautic\\' => 
        array (
            0 => __DIR__ . '/..' . '/mautic/api-library/lib',
        ),
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit9bfb4efef2e4a56c70b688b9ced90ffd::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit9bfb4efef2e4a56c70b688b9ced90ffd::$prefixDirsPsr4;

        }, null, ClassLoader::class);
    }
}
